import Head from "next/head";
import Row from "../components/Row";
import Banner from "../components/Banner";
import Header from "../components/Header";
export default function Home({ trending, action, netflix, topRated }) {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter"
          rel="stylesheet"
        />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner movies={action.results} />

      {/* movies */}
      <div className="">
        <Row title="Trending" movies={trending.results} />
        <Row title="Action movies" movies={action.results} />
        <Row title="Netflix originals" movies={netflix.results} />
        <Row title="Top rated" movies={topRated.results} />
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const [trendingRes, actionRes, netflixRes, topRatedRes] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/trending/all/week?api_key=${process.env.API_KEY}&language=en-US`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/movie?api_key=${process.env.API_KEY}&with_genres=28`
    ),
    fetch(
      `https://api.themoviedb.org/3/discover/tv?api_key=${process.env.API_KEY}&witg_network=213`
    ),
    fetch(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.API_KEY}&language=en-US`
    ),
  ]);
  const [trending, action, netflix, topRated] = await Promise.all([
    trendingRes.json(),
    actionRes.json(),
    netflixRes.json(),
    topRatedRes.json(),
  ]);
  return { props: { trending, action, netflix, topRated } };
}
